'use client';

import { useState } from 'react';
import { managerApi } from '@/lib/apiClient';
import toast from '@/lib/toast';

// ==============================|| MANAGER COUPON AUDIT PAGE ||============================== //

export default function ManagerCouponAuditPage() {
  const [couponCode, setCouponCode] = useState('');
  const [couponData, setCouponData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [searched, setSearched] = useState(false);

  const handleSearch = async (e) => {
    e.preventDefault();
    
    if (!couponCode.trim()) {
      toast.error('Please enter a coupon code');
      return;
    }

    try {
      setLoading(true);
      setSearched(true);
      const response = await managerApi.searchCoupon(couponCode.trim());
      setCouponData(response.data);
      
      if (!response.data) {
        toast.error('Coupon not found');
      }
    } catch (error) {
      if (error.response?.status === 404) {
        toast.error('Coupon not found');
        setCouponData(null);
      } else {
        toast.error(error.response?.data?.message || 'Failed to search coupon');
      }
      console.error('Search coupon error:', error);
    } finally {
      setLoading(false);
    }
  };

  const getStatusColor = (status) => {
    switch (status?.toUpperCase()) {
      case 'ACTIVE':
        return 'bg-green-100 text-green-800';
      case 'HONORED':
        return 'bg-blue-100 text-blue-800';
      case 'EXPIRED':
        return 'bg-red-100 text-red-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Coupon Audit</h1>
        <p className="text-gray-500 mt-2">Audit coupon usage and validate transactions</p>
      </div>

      {/* Search Form */}
      <div className="card bg-white dark:bg-gray-800 p-6 rounded-lg shadow">
        <form onSubmit={handleSearch} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Coupon Code
            </label>
            <div className="flex gap-3">
              <input
                type="text"
                value={couponCode}
                onChange={(e) => setCouponCode(e.target.value.toUpperCase())}
                placeholder="Enter coupon code (e.g., ABC123)"
                className="flex-1 px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 uppercase"
                disabled={loading}
              />
              <button
                type="submit"
                disabled={loading || !couponCode.trim()}
                className="px-6 py-2 bg-primary-500 text-white rounded-lg hover:bg-primary-600 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
              >
                {loading ? (
                  <>
                    <div className="h-5 w-5 animate-spin rounded-full border-2 border-white border-t-transparent"></div>
                    <span>Searching...</span>
                  </>
                ) : (
                  <>
                    <i className="ph ph-magnifying-glass"></i>
                    <span>Search</span>
                  </>
                )}
              </button>
            </div>
            <p className="text-sm text-gray-500 mt-1">
              Enter the coupon code to view its details and usage history
            </p>
          </div>
        </form>
      </div>

      {/* Coupon Details */}
      {searched && (
        couponData ? (
          <div className="card bg-white dark:bg-gray-800 p-6 rounded-lg shadow">
            <div className="space-y-4">
              {/* Header */}
              <div className="flex items-start justify-between pb-4 border-b border-gray-200 dark:border-gray-700">
                <div>
                  <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100">
                    {couponData.code}
                  </h3>
                  <p className="text-sm text-gray-500 mt-1">Coupon Details</p>
                </div>
                <span className={`px-3 py-1 text-xs font-semibold rounded ${getStatusColor(couponData.status)}`}>
                  {couponData.status || 'ACTIVE'}
                </span>
              </div>

              {/* Details Grid */}
              <div className="grid md:grid-cols-2 gap-6">
                {/* Left Column */}
                <div className="space-y-4">
                  <div>
                    <p className="text-sm text-gray-500 mb-1">Generated By</p>
                    <div className="flex items-center gap-2">
                      <i className="ph ph-user text-gray-400"></i>
                      <span className="font-medium">{couponData.generatedBy?.name || 'N/A'}</span>
                    </div>
                    {couponData.generatedBy?.email && (
                      <p className="text-sm text-gray-500 ml-6">{couponData.generatedBy.email}</p>
                    )}
                  </div>

                  <div>
                    <p className="text-sm text-gray-500 mb-1">Generated On</p>
                    <div className="flex items-center gap-2">
                      <i className="ph ph-calendar text-gray-400"></i>
                      <span className="font-medium">
                        {couponData.createdAt 
                          ? new Date(couponData.createdAt).toLocaleString('en-US', {
                              year: 'numeric',
                              month: 'short',
                              day: 'numeric',
                              hour: '2-digit',
                              minute: '2-digit'
                            })
                          : 'N/A'}
                      </span>
                    </div>
                  </div>

                  {couponData.discount && (
                    <div>
                      <p className="text-sm text-gray-500 mb-1">Discount Value</p>
                      <div className="flex items-center gap-2">
                        <i className="ph ph-percent text-gray-400"></i>
                        <span className="font-medium text-lg text-green-600">
                          {couponData.discountType === 'PERCENTAGE' 
                            ? `${couponData.discount}%`
                            : `$${couponData.discount.toFixed(2)}`}
                        </span>
                      </div>
                    </div>
                  )}
                </div>

                {/* Right Column */}
                <div className="space-y-4">
                  {couponData.honoredBy && (
                    <div>
                      <p className="text-sm text-gray-500 mb-1">Honored By</p>
                      <div className="flex items-center gap-2">
                        <i className="ph ph-user text-gray-400"></i>
                        <span className="font-medium">{couponData.honoredBy.name || 'N/A'}</span>
                      </div>
                      {couponData.honoredBy.email && (
                        <p className="text-sm text-gray-500 ml-6">{couponData.honoredBy.email}</p>
                      )}
                    </div>
                  )}

                  {couponData.honoredAt && (
                    <div>
                      <p className="text-sm text-gray-500 mb-1">Honored On</p>
                      <div className="flex items-center gap-2">
                        <i className="ph ph-calendar-check text-gray-400"></i>
                        <span className="font-medium">
                          {new Date(couponData.honoredAt).toLocaleString('en-US', {
                            year: 'numeric',
                            month: 'short',
                            day: 'numeric',
                            hour: '2-digit',
                            minute: '2-digit'
                          })}
                        </span>
                      </div>
                    </div>
                  )}

                  {couponData.expiresAt && (
                    <div>
                      <p className="text-sm text-gray-500 mb-1">Expires On</p>
                      <div className="flex items-center gap-2">
                        <i className="ph ph-clock text-gray-400"></i>
                        <span className="font-medium">
                          {new Date(couponData.expiresAt).toLocaleDateString('en-US', {
                            year: 'numeric',
                            month: 'short',
                            day: 'numeric'
                          })}
                        </span>
                      </div>
                    </div>
                  )}
                </div>
              </div>

              {/* Description */}
              {couponData.description && (
                <div className="pt-4 border-t border-gray-200 dark:border-gray-700">
                  <p className="text-sm text-gray-500 mb-2">Description</p>
                  <p className="text-gray-700 dark:text-gray-300">{couponData.description}</p>
                </div>
              )}

              {/* Customer Info */}
              {couponData.customerEmail && (
                <div className="pt-4 border-t border-gray-200 dark:border-gray-700">
                  <p className="text-sm text-gray-500 mb-2">Customer Information</p>
                  <div className="flex items-center gap-2">
                    <i className="ph ph-envelope text-gray-400"></i>
                    <span className="text-gray-700 dark:text-gray-300">{couponData.customerEmail}</span>
                  </div>
                </div>
              )}
            </div>
          </div>
        ) : (
          <div className="card bg-white dark:bg-gray-800 p-8 rounded-lg shadow text-center">
            <i className="ph ph-magnifying-glass text-gray-400 text-5xl mb-3"></i>
            <h3 className="text-lg font-semibold mb-2">Coupon Not Found</h3>
            <p className="text-gray-600 dark:text-gray-400">
              The coupon code you entered does not exist in the system.
            </p>
          </div>
        )
      )}

      {/* Info Box */}
      <div className="card bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg border-l-4 border-blue-500">
        <div className="flex items-start gap-3">
          <i className="ph ph-info text-blue-600 text-xl mt-0.5"></i>
          <div className="text-sm text-gray-700 dark:text-gray-300">
            <strong>Audit Purpose:</strong> Use this tool to verify coupon authenticity, check usage history, 
            and ensure coupons are being used correctly by employees.
          </div>
        </div>
      </div>
    </div>
  );
}

